### ISSUE TITLE
BepInEx.ResourceUnloadOptimizations is missing on the main solution

### ISSUE THREAD

**Issue by knoopx** [BepInEx/BepInEx.Utility#2]
And not being built and attached to the release

**Comment by ManlyMarco** [comment]
Looks fine to me https://github.com/BepInEx/BepInEx.Utility/blob/master/BepInEx.Utility.sln#L27
It hasn't been put into a release yet.

**Comment by knoopx** [comment]
Uuhm you are right, but still no BepInEx.ResourceUnloadOptimizations in release attachments?

**Comment by ManlyMarco** [comment]
> It hasn't been put into a release yet.

**Comment by DAOWAce** [comment]
Is this able to be used standalone with any Unity game or does it need to be specialized and that's why there's no built release for it, even 1.5 years after this issue was created?

I don't know anything about Unity or BepInEx development (nor do I have something like VS installed), so I can't compile this myself.  Tried to grab a built one from the Illusion Fixes repo but, as expected, it errors when loading into a generic game (studio error).  Still shows up in config manager, but I don't know if it's _actually_ working.  RAM usage still drops even with 'never unload' enabled, and the player.log still has "Unloading ### unused Assets to reduce memory usage."

Really wanted to see if this would fix GC stuttering in other games (notably Valheim), but sadly looks like a dead end for me.

**Comment by ManlyMarco** [comment]
It works fine, just no one bothered to make a release since it's easy to build.

**Comment by DAOWAce** [comment]
Alright, well, thanks for giving me a kick in the ass to install VS.  Loading the repo prompted for the install of things for bepinex (and unity?) development which I originally didn't know what to install, guess now I can start finally learning modding with it after all these years.

Project did indeed build extremely easily, no developer knowledge required.

**Comment by ManlyMarco** [comment]
Released in r8
